# Schema for the configuration files of the custom new module.
custom_new.settings:
  type: config_object
  label: 'custom new settings'
  mapping:
    example:
      type: string
      label: 'Example'
